name: Build and Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write 
  id-token: write  

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.12.2"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run predeploy
      
      - name: Upload project articats
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: 'github-pages'
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
